services: 
  server:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    restart: always
  caddy:
    image: caddy
    restart: always
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/config:/config
      - ./caddy/data:/data